version: '3'
services:
  fibbonacci:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: "./fibbonacci"
      dockerfile: Dockerfile.dev1
  homeservice:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: "./home_service"
      dockerfile: Dockerfile.dev1
  historyservice:
    build:
      context: .\
      dockerfile: HistoryService\HistoryService\Dockerfile
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fibbonacci
      - historyservice
      - homeservice
      - filesshare
    restart: always
    ports:
      - "4000:4000"
      - "4001:4001"
  filesshare:
    build:
      context: ./filesshare
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app/app
      - ./static:/static
