sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t irusio/PFSwChO2021/lab8/fibonnaci -f Dockerfile.dev1 .

script:
  - docker run -e CI=true irusio/PFSwChO2021/lab8/fibbonacci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Fibbonacci-test"
  env: "fibbonaccitest-env"
  bucket_name: "elasticbeanstalk-us-east-1-092118888492"
  bucket_path: "Fibbonacci"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY