version: "3"
services:
  node-app:
    build: ./api
    ports:
      - 8081:8081
    depends_on:
      - redis-server

  redis-server:
    image: redis:latest
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    hostname: redis
    ports:
      - 6379:6379